#!/bin/sh

dladm delete-etherstub skynetswitch0
dladm create-vnic -l skynetswitch0 skynet0
ipadm create-addr -T static -a 100.100.100.1/24 skynet0/t800

routeadm -e ipv4-forwarding
routeadm -u

# This might not be needed with routeadm enabling ip forwarding
cat > /etc/ipf/ipnat.conf <<EOF
map e1000g0 100.100.100.0/24 -> 0/32 portmap tcp/udp auto
map e1000g0 100.100.100.0/24 -> 0/32
EOF

