** Virtualbox
*** VBoxManage
**** convert
     VBoxManage clonehd --format VDI myserver.vmdk myserver.vdi

**** net use <drive>: \\vboxsvr\<share name>

**** internalcommands
***** compact vdi
      vboxmanage modifyhd <vdi> -compact

***** createrawvmdk
      -rawdisk
      -filename

      VBoxManage.exe internalcommands createrawvmdk -filename "C:\users\user\VirtualBox VMs\hdd-backup.vmdk" -rawdisk \\.\Volume{faaad151-4d2a-11e2-b103-806e6f6e6963}
      VBoxManage.exe internalcommands createrawvmdk -filename "C:\users\user\VirtualBox VMs\hdd-ext-1tb.vmdk" -rawdisk \\.\Volume{34a39aa5-d4f1-11df-b99f-806e6f6e6963}
      VBoxManage.exe internalcommands createrawvmdk -filename "C:\users\user\VirtualBox VMs\hdd-recovery.vmdk" -rawdisk \\.\Volume{faaad152-4d2a-11e2-b103-806e6f6e6963}

      # Try either one
      $ vboxmanage internalcommands createrawvmdk -filename "C:\\sdc" -rawdisk \\\\.\\PhysicalDrive4
      $ vboxmanage internalcommands createrawvmdk -filename "C:\\sdc" -rawdisk \\.\PhysicalDrive4

      Error: <2013-02-03 Sun 20:10>

          C:\Program Files\Oracle\VirtualBox>VBoxManage.exe internalcommands createrawvmdk -filename "C:\users\user\VirtualBox VMs\hdd-recovery.vmdk" -rawdisk \\.\Volume{faaad152-4d2a-11e2-b103-806e6f6e6963} VBoxManage.exe: error: VMDK: could not open raw disk file '\\.\Volume{faaad152-4d2a-11e2-b103-806e6f6e6963}' VBoxManage.exe: error: Error code VERR_SHARING_VIOLATION at D:\tinderbox\win-4.2\src\VBox\Storage\VMDK.cpp(3519) in function int __cdecl vmdkCreateRawImage(struct VMDKIMAGE *,struct VBOXHDDRAW *const ,unsigned __int64) VBoxManage.exe: error: Cannot create the raw disk VMDK: VERR_SHARING_VIOLATION VBoxManage.exe: error: The raw disk vmdk file was not created

***** listpartitions
      -rawdisk

      VBoxManage.exe internalcommands listpartitions -rawdisk \\?\Volume{34a39aa7-d4f1-11df-b99f-806e6f6e6963}
***** set cache flushing
      VBoxManage setextradata "VM name" "VBoxInternal/Devices/ahci/0/LUN#[x]/Config/IgnoreFlush" 0

      [x] is Port number

***** change hd uuid
      VBoxManage internalcommands sethduuid VPN_FULLLAN.vhd

**** VirtualBox Manual
***** Chapter 8. VBoxManage - http://www.virtualbox.org/manual/ch08.html
***** Chapter 9. Advanced topics - http://www.virtualbox.org/manual/ch09.html
***** Chapter 12.2.2 Responding to guest IDE/SATA flush requests - http://www.virtualbox.org/manual/ch12.html#ts_config-periodic-flush

      If desired, the virtual disk images can be flushed when the guest issues the IDE FLUSH CACHE command. Normally these requests are ignored for improved performance. The parameters below are only accepted for disk drives. They must not be set for DVD drives.


      To enable flushing for IDE disks, issue the following command:

      VBoxManage setextradata "VM name" "VBoxInternal/Devices/piix3ide/0/LUN#[x]/Config/IgnoreFlush" 0

      The value [x] that selects the disk is 0 for the master device on the first channel, 1 for the slave device on the first channel, 2 for the master device on the second channel or 3 for the master device on the second channel.


      To enable flushing for SATA disks, issue the following command:

      VBoxManage setextradata "VM name" "VBoxInternal/Devices/ahci/0/LUN#[x]/Config/IgnoreFlush" 0

      The value [x] that selects the disk can be a value between 0 and 29.

      Note that this doesn't affect the flushes performed according to the configuration described in 12.2.1. Restoring the default of ignoring flush commands is possible by setting the value to 1 or by removing the key.

***** Access to entire physical hard disk
     While this variant is the simplest to set up, you must be aware that this will give a guest operating system direct and full access to an entire physical disk. If your host operating system is also booted from this disk, please take special care to not access the partition from the guest at all. On the positive side, the physical disk can be repartitioned in arbitrary ways without having to recreate the image file that gives access to the raw disk.

     To create an image that represents an entire physical hard disk (which will not contain any actual data, as this will all be stored on the physical disk), on a Linux host, use the command

     VBoxManage internalcommands createrawvmdk -filename /path/to/file.vmdk
  	   -rawdisk /dev/sda

     This creates the image /path/to/file.vmdk (must be absolute), and all data will be read and written from /dev/sda.

     On a Windows host, instead of the above device specification, use e.g. \\.\PhysicalDrive0. On a Mac OS X host, instead of the above device specification use e.g. /dev/disk1. Note that on OS X you can only get access to an entire disk if no volume is mounted from it.

     Creating the image requires read/write access for the given device. Read/write access is also later needed when using the image from a virtual machine. On some host platforms (e.g. Windows Vista and later), raw disk access may be restricted and not permitted by the host OS in some situations.

     Just like with regular disk images, this does not automatically attach the newly created image to a virtual machine. This can be done with e.g.

     VBoxManage storageattach WindowsXP --storagectl "IDE Controller"
  	   --port 0 --device 0 --type hdd --medium /path/to/file.vmdk

     When this is done the selected virtual machine will boot from the specified physical disk.

***** Access to individual physical hard disk partitions
     This "raw partition support" is quite similar to the "full hard disk" access described above. However, in this case, any partitioning information will be stored inside the VMDK image, so you can e.g. install a different boot loader in the virtual hard disk without affecting the host's partitioning information. While the guest will be able to see all partitions that exist on the physical disk, access will be filtered in that reading from partitions for which no access is allowed the partitions will only yield zeroes, and all writes to them are ignored.

     To create a special image for raw partition support (which will contain a small amount of data, as already mentioned), on a Linux host, use the command

     VBoxManage internalcommands createrawvmdk -filename /path/to/file.vmdk
   	  -rawdisk /dev/sda -partitions 1,5

     As you can see, the command is identical to the one for "full hard disk" access, except for the additional -partitions parameter. This example would create the image /path/to/file.vmdk (which, again, must be absolute), and partitions 1 and 5 of /dev/sda would be made accessible to the guest.

     VirtualBox uses the same partition numbering as your Linux host. As a result, the numbers given in the above example would refer to the first primary partition and the first logical drive in the extended partition, respectively.

     On a Windows host, instead of the above device specification, use e.g. \\.\PhysicalDrive0. On a Mac OS X host, instead of the above device specification use e.g. /dev/disk1. Note that on OS X you can only use partitions which are not mounted (eject the respective volume first). Partition numbers are the same on Linux, Windows and Mac OS X hosts.

     The numbers for the list of partitions can be taken from the output of

     VBoxManage internalcommands listpartitions -rawdisk /dev/sda

     The output lists the partition types and sizes to give the user enough information to identify the partitions necessary for the guest.

     Images which give access to individual partitions are specific to a particular host disk setup. You cannot transfer these images to another host; also, whenever the host partitioning changes, the image must be recreated.

     Creating the image requires read/write access for the given device. Read/write access is also later needed when using the image from a virtual machine. If this is not feasible, there is a special variant for raw partition access (currently only available on Linux hosts) that avoids having to give the current user access to the entire disk. To set up such an image, use

     VBoxManage internalcommands createrawvmdk -filename /path/to/file.vmdk
   	  -rawdisk /dev/sda -partitions 1,5 -relative

     When used from a virtual machine, the image will then refer not to the entire disk, but only to the individual partitions (in the example /dev/sda1 and /dev/sda5). As a consequence, read/write access is only required for the affected partitions, not for the entire disk. During creation however, read-only access to the entire disk is required to obtain the partitioning information.

     In some configurations it may be necessary to change the MBR code of the created image, e.g. to replace the Linux boot loader that is used on the host by another boot loader. This allows e.g. the guest to boot directly to Windows, while the host boots Linux from the "same" disk. For this purpose the -mbr parameter is provided. It specifies a file name from which to take the MBR code. The partition table is not modified at all, so a MBR file from a system with totally different partitioning can be used. An example of this is

     VBoxManage internalcommands createrawvmdk -filename /path/to/file.vmdk
   	  -rawdisk /dev/sda -partitions 1,5 -mbr winxp.mbr

     The modified MBR will be stored inside the image, not on the host disk.

     The created image can be attached to a storage controller in a VM configuration as usual.

**** VBoxManage
***** VBoxManage convertfromraw --format VDI [filename].img [filename].vdi

***** VBoxManage dhcpserver remove --netname <network_name>

***** VBoxManage list dhcpservers

***** VBoxManage list vms
      "Windows 10 Enterprise Preview" {6cf8093e-8bd5-43b4-9aa2-af60760f33ce}
      "Windows on this box" {78fa25e1-5675-4004-b0e6-2077f586ba73}
      "Windows XP SP2" {0675ea6d-443a-4158-8ea9-73982a4bd8a1}
      "Win7" {46422121-c221-4d02-a8d4-046303d03a91}
      "OpenVPN" {8ceed512-f58e-4343-bd16-46af7407ff0a}
      "Windows 8" {c92736e4-8445-4c23-b4ce-aa0e3c692abf}
      "OpenVPN Access Server 210" {eac112bb-6bfd-473e-afe9-0e7705c0b873}

***** VBoxManage modifyvm "VM name" --pciattach 02:00.0@01:05.0

***** VBoxManage modifyvm "VM name" --pcidetach 02:00.0

***** VBoxManage modifyvm “MyVM” –nic1 bridged –nictype1 82540EM –bridgeadapter1 eth0

      AMD PCNet PCI II = Am79C970A
      AMD PCNet FAST III = Am79C973 (the default)
      Intel PRO/1000 MT Desktop = 82540EM
      Intel PRO/1000 T Server = 82543GC
      Intel PRO/1000 MT Server = 82545EM
      Paravirtualized network adapter = virtio-net

***** VBoxManage natnetwork remove --netname <network_name>

***** VBoxManage startvm "OpenVPN Access Server 210"

***** VBoxManage startvm eac112bb-6bfd-473e-afe9-0e7705c0b873

**** Install VBox guest addons
     apt-get install dkms build-essential linux-headers-$(uname -r)

**** Mounting VBox shared folders
     # Automounted shared folders will be mounted to /media

     # Using fstab
     /media/vbox-share /desired/mount/point bind defaults,bind 0 0
